---
abstract: 'Naive Bayes Classifier'
author:
  - 'Data-Classifier-NaiveBayes <logie@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300013, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Classifier-NaiveBayes
requires:
  Lingua::Stem::Snowball: 0
  List::Util: 0
  Moose: 0
  MooseX::Types::LoadableClass: 0
version: 0.002
